services:
  - type: web
    name: shiva-shakti
    env: python
    region: oregon
    plan: starter
    repo: https://github.com/Basava1514/construction-site
    branch: main
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: bash entrypoint.sh
    envVars:
      - key: DJANGO_DEBUG
        value: 'False'
      - key: DJANGO_SECRET_KEY
        value: ''
      - key: ALLOWED_HOSTS
        value: ''
    healthCheckPath: /healthz/
    healthCheckIntervalSeconds: 10
    healthCheckTimeoutSeconds: 5

databases:
  - name: shiva-shakti-db
    plan: starter
